name: quantum_muscle
description: A new age of fitness

publish_to: "none"

version: 1.5.0

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.5
  permission_handler: ^11.0.1
  cloud_firestore: ^4.13.1
  firebase_auth: ^4.14.0
  firebase_storage: ^11.5.1
  image_picker: ^1.0.4
  eva_icons_flutter: ^3.1.0
  firebase_core: ^2.22.0
  go_router: ^13.0.1
  responsive_framework: ^1.1.1
  flutter_riverpod: ^2.4.6
  uuid: ^4.2.1
  slimy_card:
    git:
      url: https://github.com/OmarHosamCodes/SlimyCard-Animated-Flutter-Package/
  intl: ^0.18.1
  url_strategy: ^0.2.0
  flutter_animate: ^4.3.0
  floating_action_bubble: ^1.1.4
  cached_network_image: ^3.3.0
  flutter_staggered_grid_view:
    git:
      url: https://github.com/OmarHosamCodes/flutter_staggered_grid_view/
  flutter_hooks: ^0.20.4
  hooks_riverpod: ^2.4.9
  pattern_background: ^1.1.3
  fl_chart: ^0.66.0
  connectivity_plus: ^5.0.2
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/images/loginImg.png
    - assets/images/registerImg.png
    - assets/images/mainVector.png

  fonts:
    - family: ubuntu
      fonts:
        - asset: assets/font/ubuntu.ttf
flutter_intl:
  enabled: true
# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/icon/icon.png"
#   web:
#     generate: true
#     image_path: "assets/icon/icon.png"
#     background_color: "#212121"
#     theme_color: "#212121"
# flutter_native_splash:
#   # dart run flutter_native_splash:create
#   color: "#212121"
#   image: assets/icon/icon.png
#   android_12:
#     image: assets/icon/icon.png
#     color: "#212121"
#   android: true
#   ios: true
#   web: true
#   android_gravity: center
#   ios_content_mode: center
#   web_image_mode: center
#   fullscreen: true
