name: quantum_muscle
description: A new age of fitness

publish_to: "none"

version: 2.0.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.13.1
  cupertino_icons: ^1.0.2
  eva_icons_flutter: ^3.1.0
  expandable: ^5.0.1
  fade_shimmer: ^2.2.0
  firebase_analytics: ^10.8.0
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  firebase_storage: ^11.5.1
  fl_chart: ^0.66.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.6
  flutter_staggered_grid_view:
    git:
      url: https://github.com/OmarHosamCodes/flutter_staggered_grid_view/

  go_router: ^13.0.1
  image_picker: ^1.0.4
  intl: ^0.18.1
  pattern_background: ^1.1.3
  permission_handler: ^11.0.1
  slimy_card:
    git:
      url: https://github.com/OmarHosamCodes/SlimyCard-Animated-Flutter-Package/
  url_strategy: ^0.2.0
  responsive_framework: ^1.1.1
  uuid: ^4.3.3
  marquee_text: ^2.5.0+1
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.5
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/images/loginImg.png
    - assets/images/registerImg.png

  fonts:
    - family: ubuntu
      fonts:
        - asset: assets/font/ubuntu.ttf
flutter_intl:
  enabled: true
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#191919"
    theme_color: "#191919"
flutter_native_splash:
  # dart run flutter_native_splash:create
  color: "#191919"
  image: assets/icon/icon.png
  android_12:
    image: assets/icon/icon.png
    color: "#191919"
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  fullscreen: true
