mixin AnalyticsEventNamesConstants {
  static const String error = 'error';
  static const String success = 'success';

  static const String login = 'login';
  static const String logout = 'logout';
  static const String register = 'register';
  static const String forgotPassword = 'forgot_password';
  static const String changePassword = 'change_password';
  static const String changeProfile = 'change_profile';
  static const String changeLanguage = 'change_language';
  static const String changeNotification = 'change_notification';
  static const String addWorkout = 'add_Workout';
  static const String removeWorkout = 'remove_Workout';
  static const String addExercise = 'add_Exercise';
  static const String removeExercise = 'remove_Exercise';
  static const String addSet = 'add_Set';
  static const String removeSet = 'remove_Set'; // for future use
  static const String changeSet = 'change_Set';
  static const String addProgram = 'add_Program';
  static const String removeProgram = 'remove_Program';
  static const String addProgramWorkout = 'add_Program_Workout';
  static const String removeProgramWorkout = 'remove_Program_Workout';
  static const String addProgramExercise = 'add_Program_Exercise';
  static const String removeProgramExercise = 'remove_Program_Exercise';
  static const String addProgramSet = 'add_Program_Set';
  static const String removeProgramSet = 'remove_Program_Set';
  static const String changeProgramSet = 'change_Program_Set';
  static const String routingError = 'routing_error';
  static const String addTrainee = 'add_Trainee';
  static const String removeTrainee = 'remove_Trainee';
  static const String sendRequest = 'send_Request';
  static const String acceptRequest = 'accept_Request';
  static const String declineRequest = 'decline_Request';
  static const String addContent = 'add_Content';
  static const String removeContent = 'remove_Content';
  static const String follow = 'follow';
  static const String unfollow = 'unfollow';
  static const String addComment = 'add_Comment';
  static const String removeComment = 'remove_Comment';
  static const String addLike = 'add_Like';
  static const String removeLike = 'remove_Like';
}
